services:
  mcp-gateway:
    image: docker/mcp-gateway:v0.42.0
    command:
      - --servers=duckduckgo
      - --transport=streaming
    ports:
      - 8811:8811
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
