tls:
  certificates:
    - certFile: /certs/mft-sub/fullchain.pem
      keyFile: /certs/mft-sub/privkey.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/mft-sub/fullchain.pem
        keyFile: /certs/mft-sub/privkey.pem
