#!/bin/sh
# =============================================================================
# restore-env.sh — validate AND fix .env files from a backup, then restore
# =============================================================================
# Usage:
#   bash scripts/restore-env.sh              # auto-detect latest backup
#   bash scripts/restore-env.sh --fix        # auto-fix issues before restore
#   bash scripts/restore-env.sh --dry-run    # validate only, no restore
#   bash scripts/restore-env.sh --fix --dry-run  # show what would be fixed
#
# Fix mode corrects:
#   - Quoted values:          KEY="value"    → KEY=value
#   - Whitespace around =:    KEY = value    → KEY=value
#   - Trailing whitespace:    KEY=value   \n → KEY=value\n
#   - Windows line endings:   KEY=value\r\n  → KEY=value\n
#   - YAML booleans:          KEY=true       → KEY=true  (kept — valid)
#   - YAML braces:            KEY={obj}      → flagged, not auto-fixed
#   - Empty values:           KEY=           → kept (valid)
# =============================================================================

set -e

# ── Defaults ──────────────────────────────────────────────────────────────────
NEW_REPO="/volume1/docker/dockge"
BACKUP_ROOT="/volume1/docker/archive"
FIX_MODE=0
DRY_RUN=0

# ── Argument parsing ──────────────────────────────────────────────────────────
for arg in "$@"; do
	case "$arg" in
	--fix) FIX_MODE=1 ;;
	--dry-run) DRY_RUN=1 ;;
	--help)
		sed -n '2,20p' "$0" | sed 's/^# //'
		exit 0
		;;
	*)
		echo "Unknown argument: $arg (use --fix, --dry-run, --help)"
		exit 1
		;;
	esac
done

# ── Locate backup ─────────────────────────────────────────────────────────────
# shellcheck disable=SC2012 # Backup directory names are generated by this script and sort correctly with ls -dt.
BACKUP_DIR=$(ls -dt "$BACKUP_ROOT"/dockge-backup-* 2>/dev/null | head -n 1)

if [ -z "$BACKUP_DIR" ]; then
	echo "ERROR: No backup folder found under $BACKUP_ROOT"
	exit 1
fi

echo "==> Backup:   $BACKUP_DIR"
echo "==> Repo:     $NEW_REPO"
echo "==> Fix mode: $([ "$FIX_MODE" -eq 1 ] && echo YES || echo NO)"
echo "==> Dry run:  $([ "$DRY_RUN" -eq 1 ] && echo YES || echo NO)"
echo ""

# ── Temp dir for fixed copies ─────────────────────────────────────────────────
TMPDIR_FIXED=$(mktemp -d)
trap 'rm -rf "$TMPDIR_FIXED"' EXIT

# ── Validate and optionally fix a single .env file ────────────────────────────
# Returns 0 if clean (or fixable), 1 if has unfixable errors
process_env() {
	src="$1"
	out="$2" # output path for fixed version
	label="${src#"$BACKUP_DIR"/}"

	lineno=0
	file_errors=0
	file_fixes=0

	: >"$out" # create/truncate output

	while IFS= read -r raw || [ -n "$raw" ]; do
		lineno=$((lineno + 1))
		line="$raw"

		# ── Strip Windows CR ──────────────────────────────────────────────────
		line=$(printf '%s' "$line" | tr -d '\r')
		if [ "$line" != "$raw" ] && [ "$FIX_MODE" -eq 1 ]; then
			printf '  FIX  line %3d: stripped \\r (Windows line ending)\n' "$lineno"
			file_fixes=$((file_fixes + 1))
		fi

		# ── Pass through blank lines and comments ─────────────────────────────
		case "$line" in
		'' | '#'* | ' '#*)
			printf '%s\n' "$line" >>"$out"
			continue
			;;
		esac

		# ── Must match KEY=value ──────────────────────────────────────────────
		if ! printf '%s' "$line" | grep -Eq '^[A-Za-z_][A-Za-z0-9_]*=.*$'; then
			# Try to fix: KEY = value → KEY=value
			fixed=$(printf '%s' "$line" | sed 's/[[:space:]]*=[[:space:]]*/=/')
			if printf '%s' "$fixed" | grep -Eq '^[A-Za-z_][A-Za-z0-9_]*=.*$' &&
				[ "$FIX_MODE" -eq 1 ]; then
				printf '  FIX  line %3d: whitespace around = → %s\n' "$lineno" "$fixed"
				line="$fixed"
				file_fixes=$((file_fixes + 1))
			else
				printf '  ERROR line %3d: invalid format → %s\n' "$lineno" "$line"
				file_errors=$((file_errors + 1))
				printf '%s\n' "$line" >>"$out"
				continue
			fi
		fi

		key=$(printf '%s' "$line" | cut -d= -f1)
		val=$(printf '%s' "$line" | cut -d= -f2-)

		# ── Strip surrounding double quotes: KEY="value" → KEY=value ─────────
		case "$val" in
		'"'*'"')
			stripped=$(printf '%s' "$val" | sed 's/^"//;s/"$//')
			if [ "$FIX_MODE" -eq 1 ]; then
				printf '  FIX  line %3d: removed double quotes → %s=%s\n' \
					"$lineno" "$key" "$stripped"
				val="$stripped"
				line="${key}=${val}"
				file_fixes=$((file_fixes + 1))
			else
				printf '  WARN line %3d: quoted value (use --fix) → %s\n' \
					"$lineno" "$line"
			fi
			;;
		'"'*)
			printf '  ERROR line %3d: unmatched double quote → %s\n' "$lineno" "$line"
			file_errors=$((file_errors + 1))
			;;
		esac

		# ── Strip surrounding single quotes: KEY='value' → KEY=value ─────────
		case "$val" in
		"'"*"'")
			stripped=$(printf '%s' "$val" | sed "s/^'//;s/'$//")
			if [ "$FIX_MODE" -eq 1 ]; then
				printf '  FIX  line %3d: removed single quotes → %s=%s\n' \
					"$lineno" "$key" "$stripped"
				val="$stripped"
				line="${key}=${val}"
				file_fixes=$((file_fixes + 1))
			else
				printf '  WARN line %3d: single-quoted value (use --fix) → %s\n' \
					"$lineno" "$line"
			fi
			;;
		esac

		# ── Strip trailing whitespace ─────────────────────────────────────────
		trimmed=$(printf '%s' "$line" | sed 's/[[:space:]]*$//')
		if [ "$trimmed" != "$line" ] && [ "$FIX_MODE" -eq 1 ]; then
			printf '  FIX  line %3d: stripped trailing whitespace → %s\n' \
				"$lineno" "$trimmed"
			line="$trimmed"
			file_fixes=$((file_fixes + 1))
		fi

		# ── YAML brace syntax (cannot auto-fix) ──────────────────────────────
		case "$val" in
		'{'* | *'}')
			printf '  ERROR line %3d: YAML brace syntax not allowed → %s\n' \
				"$lineno" "$line"
			file_errors=$((file_errors + 1))
			;;
		esac

		printf '%s\n' "$line" >>"$out"
	done <"$src"

	if [ "$file_fixes" -gt 0 ]; then
		printf '  --> %d fix(es) applied to %s\n' "$file_fixes" "$label"
	fi
	if [ "$file_errors" -gt 0 ]; then
		printf '  --> %d unfixable error(s) in %s\n' "$file_errors" "$label"
		return 1
	fi
	return 0
}

# ── Main loop ─────────────────────────────────────────────────────────────────
TOTAL_ERRORS=0
ENV_FILES=$(find "$BACKUP_DIR" -name ".env")

if [ -z "$ENV_FILES" ]; then
	echo "No .env files found in $BACKUP_DIR"
	exit 0
fi

for src in $ENV_FILES; do
	label="${src#"$BACKUP_DIR"/}"
	echo "── $label"

	fixed_copy="${TMPDIR_FIXED}/${label}"
	mkdir -p "$(dirname "$fixed_copy")"

	if ! process_env "$src" "$fixed_copy"; then
		TOTAL_ERRORS=$((TOTAL_ERRORS + 1))
	fi
	echo ""
done

# ── Abort if unfixable errors ─────────────────────────────────────────────────
if [ "$TOTAL_ERRORS" -gt 0 ]; then
	echo "==> Validation FAILED — $TOTAL_ERRORS file(s) have unfixable errors"
	echo "==> Aborting restore. Fix the errors above and re-run."
	exit 1
fi

# ── Dry run stops here ────────────────────────────────────────────────────────
if [ "$DRY_RUN" -eq 1 ]; then
	echo "==> Dry run complete — no files written"
	exit 0
fi

# ── Restore fixed files ───────────────────────────────────────────────────────
echo "==> All .env files valid — restoring to $NEW_REPO"
echo ""

for src in $ENV_FILES; do
	label="${src#"$BACKUP_DIR"/}"
	dest="$NEW_REPO/$label"
	fixed_copy="${TMPDIR_FIXED}/${label}"

	echo "  Restoring: $label"
	mkdir -p "$(dirname "$dest")"

	# Use fixed copy if fix mode, original otherwise
	if [ "$FIX_MODE" -eq 1 ]; then
		cp "$fixed_copy" "$dest"
	else
		cp "$src" "$dest"
	fi
done

echo ""
echo "==> Fixing permissions"
chown -R "$(whoami):users" "$NEW_REPO"
chmod -R u+rwX "$NEW_REPO"

echo ""
echo "==> Done!"
echo "    Backup used: $BACKUP_DIR"
echo "    Files restored: $(printf '%s\n' "$ENV_FILES" | wc -l | tr -d ' ')"
